package me.angeschossen.lands.api.enums;

public enum LandsAction {
    BLOCK_BREAK,
    BLOCK_PLACE,
    ATTACK_PLAYER,
    ATTACK_ANIMAL,
    BLOCK_IGNITE,
    INTERACT_GENERAL,
    INTERACT_MECHANISM,
    INTERACT_CONTAINER,
    INTERACT_DOOR,
    PLAYER_TRUST,
    PLAYER_UNTRUST,
    PLAYER_SETROLE,
    LAND_CLAIM,
    LAND_CLAIM_BORDER,
    LAND_SPAWN_SET,
    LAND_SPAWN_TELEPORT,
    LAND_RENAME,
    SETTING_EDIT_LAND,
    SETTING_EDIT_ROLE,
    SETTING_EDIT_ADVANCED,
    SETTING_EDIT_TAXES,
    SETTING_EDIT_VARIOUS,
    FLY

}
